# Chances for an area to be infected
# Formatted: 5 as in 1/5
server:
  infectionRate:
    BADLANDS: 10
    BADLANDS_PLATEAU: 10
    BAMBOO_JUNGLE: 10
    BIRCH_FOREST: 10
    DESERT: 20
    DARK_FOREST: 50
    FOREST: 10
    JUNGLE: 10
    MOUNTAINS: 30
    NETHER_WASTES: 5
    SWAMP: 5
    PLAINS: 10
    TAIGA: 10
    THE_END: 5
    MUSHROOM_FIELDS: 2

# DO NOT TOUCH
globalInfectionIndex: 0
